### ISSUE TITLE
The package lacks a file for running main.m

### ISSUE THREAD

**Issue by brianpkeane** [alexteghipco/Correlogram#1]
The file: LockedCerebellumData_healthy.csv

**Comment by alexteghipco** [comment]
Ah yes, so the main.m file is just an example of how you might set up your data for plotting but it's not very intuitive. I'll have a better tutorial file up sometime soon. 

LockedCerebellumData_healthy.csv is only used to define 'data' and 'data2' variables. You can load in your own data and call it by the same names, these two variables are just the matrices you want to get correlations from (rows in both matrices should correspond to samples and columns to variables). The only other wrinkle is that 'data' and 'data2' are table variables so if you just have a regular matrix you'll need to use array2table() on it. Once you do that you should be able to follow along the main.m code (starting from line 19).

**Comment by brianpkeane** [comment]
Thanks!  Yes, I figured that.  I successfully used your code already and will be sure to cite you when we submit.  One quick question:  Without me having to go through the code itself, is there an easy way to put a p value and hedges’ g value (or cohen’s d) for comparing groups on the mean value of a variable for each histogram in the correlogram?  Again, I can figure it out, but I suspect this is something you could do in 10 minutes.

Brian




From: alexteghipco ***@***.***>
Reply-To: alexteghipco/Correlogram ***@***.***>
Date: Thursday, April 13, 2023 at 11:24 AM
To: alexteghipco/Correlogram ***@***.***>
Cc: brianpkeane ***@***.***>, Author ***@***.***>
Subject: Re: [alexteghipco/Correlogram] The package lacks a file for running main.m (Issue #1)


Ah yes, so the main.m file is just an example of how you might set up your data for plotting but it's not very intuitive. I'll have a better tutorial file up sometime soon.

LockedCerebellumData_healthy.csv is only used to define 'data' and 'data2' variables. You can load in your own data and call it by the same names, these two variables are just the matrices you want to get correlations from (rows in both matrices should correspond to samples and columns to variables). The only other wrinkle is that 'data' and 'data2' are table variables so if you just have a regular matrix you'll need to use array2table() on it. Once you do that you should be able to follow along the main.m code (starting from line 19).

**Comment by alexteghipco** [comment]
That's a really great idea, I just pushed an update that should do this, let me know if you run into any problems. Lines 85-104 in main.m have been changed now and you can use this code to get cohen's d and two-sample t-test significances and update the corresponding tmpTxt and tmpTxtClr variables that get passed on to correlogram. You now have to make sure the flag for annotating histograms is on for correlogram (see line 106; 'plotDiagTxt'). 

I had to implement cohen's d manually but if you want hedges' g or to use matlab's internal cohen's d computation you can substitute lines 89-91 with meanEffectSize.m (only available in 2022a+ so I'm avoiding it for now)

I also added a DOI from zenodo and a citation file so that if you do end up citing this repository there will always be a link to the exact code you used. 

Jfyi I'm going to be whipping this repository into better shape in the coming weeks so if you have any other neat suggestions lmk!

**Comment by brianpkeane** [comment]
Thanks!  Here are a few other suggestions (and things I have been changing):

  *   Have labels only on the outer edge of each row and each column for simplicity; eliminate the “Density” label since that will be implicit and can be clarified in the caption as well.
  *   Give option to have square scattergraphs; right now they are longer horizontally than vertically.  Or better, give an option to specify the aspect ratio of each panel
  *   Right now, the file does not handle very small values (e.g., 1E-5) for the matrices; I think it is rounding these values to zero when establishing upper and lower limits to the axes, which produces errors.  I have to multiply the matrices by a constant to get the figure output.
  *   Allow p values above .05 to be given exact values p=.06 rather than p>.05

Otherwise, looks great!

From: alexteghipco ***@***.***>
Reply-To: alexteghipco/Correlogram ***@***.***>
Date: Thursday, April 13, 2023 at 4:23 PM
To: alexteghipco/Correlogram ***@***.***>
Cc: brianpkeane ***@***.***>, Author ***@***.***>
Subject: Re: [alexteghipco/Correlogram] The package lacks a file for running main.m (Issue #1)


That's a really great idea, I just pushed an update that should do this, let me know if you run into any problems. Lines 85-104 in main.m have been changed now and you can use this code to get cohen's d and two-sample t-test significances and update the corresponding tmpTxt and tmpTxtClr variables that get passed on to correlogram. You now have to make sure the flag for annotating histograms is on for correlogram (see line 106; 'plotDiagTxt').

I had to implement cohen's d manually but if you want hedges' g or to use matlab's internal cohen's d computation you can substitute lines 89-91 with meanEffectSize.m (only available in 2022a+ so I'm avoiding it for now)

I also added a DOI from zenodo and a citation file so that if you do end up citing this repository there will always be a link to the exact code you used.

Jfyi I'm going to be whipping this repository into better shape in the coming weeks so if you have any other neat suggestions lmk!

**Comment by alexteghipco** [comment]
All excellent suggestions, thanks! Will be adding them in
